version: "3"

services:
  gpvc_db:
    image: mysql:latest
    container_name: gpvc_db
    volumes:
      - ./data/mysql/gpvc:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  gpvc:
    image: gpvc:latest
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: ${HOST}
    container_name: gpvc
    depends_on:
      - gpvc_db

networks:
  default:
    external:
      name: nginx-proxy